name: main_workflow
on:
    push:
        branches:
            - nodejs_nodeversions_job 
jobs:
    linter-execution:
      runs-on:  ubuntu-latest
      strategy:
        matrix:
          node-version: [16, 18, 20]
      steps:  
      # Step 1 Checkout code
       - name: Checkout code 
         uses: actions/checkout@v3
      # Step 2 Setup node version
       - name: Setting node version
         uses: actions/setup-node@v3
         with:
           node-version: ${{matrix.node-version}}

      # Step 3 Linter execution
       -  name: Linter execution
          uses: github/super-linter@v4  
          env:
            DEFAULT_BRANCH: node-test_job
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
            LINTER_RULES_PATH:  /
            JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
            VALIDATE_JAVASCRIPT_ES: true
    test-exection:
      runs-on: ubuntu-latest
      needs: linter-execution
      steps:
        - name: Chekout Code
          uses: actions/checkout@v3
        - name:  Install Jest
          run: npm install Jest --legacy-peer-deps
        - name: Run Jest Test
          run: npm run test
