name: main_workflow
on:
    push:
        branches:
            - nodejs_test_job 
jobs:
    linter-execution:
      runs-on:  ubuntu-latest
      steps:  
      # Step 1 Checkout code
       - name: checkout code 
         uses: actions/checkout@v2
      # Step 2 Linter execution
       -  name: Linter execution
          uses: github/super_linter@v4  
          env:
            DEFAULT_BRANCH: nodejs_example
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
            LINTER_RULES_PATH:  /
            JAVASCRIPT_ES_CONFIG_FILE: .eslinctrc.json
            VALIDATE_JAVASCRIPT_ES: true
    test-exection:
      runs-on: ubuntu-latest
      needs: linter-execution
      steps:
        - name: Chekout Code
          uses: actions/checkout@v2
        - name:  Install Jest
          run: npm install Jest --legacy-peer-deps
        - name: Run Jest Test
          run: npm run test
