name: Send Telegram Message

on:
  push:
    branches:
      - send_telegram_action

jobs:
  envio_missatge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Send Telegram Message
        run: npm run send-telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_ID_USER: ${{ secrets.TELEGRAM_ID_USER }}
